import React from "react";
import type { Metadata } from "next";
import { Open_Sans, Rubik } from "next/font/google";

import '../styles/globals.css';
import { ToastContainer } from "react-toastify";
import PathnameWrapper from "components/PathnameWrapper";

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-open-sans",
});

const rubik = Rubik({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-rubik",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} ${rubik.variable} antialiased`}>
        <PathnameWrapper>
          <ToastContainer autoClose={1500} />
          {children}
        </PathnameWrapper>
      </body>
    </html>
  );
}
